services:
  db:
    image: postgres:15.1-alpine3.17
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432
volumes:
  postgresql-data:
